// Articles and publications, indexed here — published elsewhere.
//
// Thought leadership lives on papanguer.com; that was settled deliberately, and
// nothing here reproduces an article's body. These pages are an index: title,
// date, and the opening line, linking out to the canonical piece. An excerpt
// plus a link is a normal index page; a copy of the article would be duplicate
// content competing with the original.
//
// ARTICLES is generated by `npm run sync:writing`, which reads
// papanguer.com/writing/ and rewrites the array below. It is committed rather
// than fetched at build time on purpose: the prerender already fails the build
// on error, and coupling deploys to an external site being up would mean
// papanguer.com going down takes pawadata.com's deploys with it.
//
// Articles publish weekly, so run the sync before a deploy if the list matters.
// Stale-but-correct beats fresh-but-fragile; the "all articles" link is always
// current regardless.

export const WRITING_INDEX = 'https://papanguer.com/writing/';
export const BOOKS_INDEX = 'https://papanguer.com/#books';

// --- BEGIN GENERATED: npm run sync:writing ---
export const ARTICLES = [
  {
    title: 'The Governance Crisis: The Turning Point',
    date: '2026-09-01',
    readingTime: '9 min',
    excerpt: 'The absence of those four pages had cost the company its reputation and would ultimately cost it $247 million in fines, settlements, and remediation.',
    href: 'https://papanguer.com/writing/the-governance-crisis-the-turning-point/',
  },
  {
    title: 'The Governance Crisis: The Reckoning Deepens',
    date: '2026-08-25',
    readingTime: '5 min',
    excerpt: 'By 5:45, every director was present, either in person or via the secure video link that the company maintained for situations exactly like this, though no one had ever imagined a situation exactly like this.',
    href: 'https://papanguer.com/writing/the-governance-crisis-the-reckoning-deepens/',
  },
  {
    title: 'The Governance Crisis: The Reckoning',
    date: '2026-08-18',
    readingTime: '5 min',
    excerpt: 'Under Quebec’s Law 25, we face administrative monetary penalties of up to $25 million or four percent of worldwide turnover, whichever is greater.',
    href: 'https://papanguer.com/writing/the-governance-crisis-the-reckoning/',
  },
  {
    title: 'The Governance Crisis: The Call',
    date: '2026-08-11',
    readingTime: '6 min',
    excerpt: 'The phone rang at 5:47 on a Tuesday morning. Sixty-two million policyholder records, four privacy commissioners, and a junior analyst who could see all of it from a standard dashboard login.',
    href: 'https://papanguer.com/writing/the-governance-crisis-the-call/',
  },
];
// --- END GENERATED ---

// Books change a few times a year, so this stays hand-maintained. Every field
// is taken from papanguer.com rather than written fresh — ISBNs, page counts and
// publishers are the kind of detail that must not be approximated.
export const PUBLICATIONS = [
  {
    id: 'winning-the-moments',
    status: 'available',
    title: 'Winning the Moments That Matter',
    subtitle: "A Sales Engineer's Playbook for Mastering Every Stage of the Deal",
    description:
      'Eleven enterprise deal stories drawn from 25 years of real technical selling. Every character is fictional. Every lesson is real. Each story captures a moment where the deal turned, for better or worse, and teaches what separates sellers who close from sellers who demo.',
    meta: '151 pages · Kindle and paperback · ISBN 978-1-0696288-0-0 · Nguer Press',
    links: [
      { label: 'Amazon.com', href: 'https://www.amazon.com/dp/1069628808' },
      { label: 'Amazon.ca', href: 'https://www.amazon.ca/dp/1069628808' },
    ],
  },
  {
    id: 'accountability-gap',
    status: 'forthcoming',
    title: 'The Accountability Gap',
    subtitle: 'Closing the distance between agreement and ownership',
    description:
      'Every stalled transformation has the same fingerprint: a room full of people who agree it matters and no one who owns making it happen. This book names that gap and gives leaders the mechanics to close it.',
    meta: 'PaWa Press · September 2026 · For executives, transformation leaders, and boards',
    links: [],
  },
  {
    id: 'winning-the-moments-hardcover',
    status: 'forthcoming',
    title: 'Winning the Moments That Matter — Hardcover edition',
    subtitle: 'The playbook, built for the shelf it will actually live on',
    description:
      'The same eleven stories and seven cheat sheets, in a hardcover edition made for the desk of a presales leader who reaches for it before a deal review.',
    meta: 'September 2026 · ISBN 978-1-0694628-9-3 · Distributed via IngramSpark',
    links: [],
  },
];
